plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.androidx.room3)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)      // version == Kotlin version (lockstep)
    alias(libs.plugins.android.kmp.library)   // AGP 9 KMP library plugin — needs a JDK AGP 9 supports
}

kotlin {
    // AGP's KMP library target. No host/device test builders are enabled, so commonTest is not
    // compiled for Android here — Compose UI tests run on the JVM (desktop) and iOS targets.
    androidLibrary {
        namespace = "com.example.userprofile"
        compileSdk = 36
        minSdk = 24
    }
    jvm()
    iosArm64 { binaries.framework { baseName = "UserProfile"; isStatic = true } }
    iosSimulatorArm64 { binaries.framework { baseName = "UserProfile"; isStatic = true } }

    explicitApi()

    // The ONE recorded reason this flag is present: Room 3's documented KMP pattern requires an
    // `expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase>` whose
    // `actual` is generated by KSP. expect/actual *classes* are Beta and warn without this.
    // Do not add this flag to suppress a warning on an expect class you wrote yourself —
    // use an interface + DI instead (references/kmp/project-structure.md).
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.client.auth)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.androidx.datastore.core)
            implementation(libs.androidx.datastore.core.okio)
            implementation(libs.androidx.datastore.preferences.core)
            implementation(libs.okio)
            implementation(libs.androidx.room3.runtime)
            implementation(libs.androidx.sqlite.bundled)
            // Compose Multiplatform. On Android these resolve to Google's androidx artifacts.
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)   // Skiko backend for the JVM target
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.turbine)
            implementation(libs.koin.test)
            implementation(libs.ktor.client.mock)
            implementation(libs.okio.fakefilesystem)
            implementation(libs.compose.ui.test)
        }
        jvmTest.dependencies {
            implementation(libs.androidx.room3.testing)    // MigrationTestHelper (file-system based)
        }
    }
}

compose.resources {
    packageOfResClass = "com.example.userprofile.resources"
    publicResClass = false
}

// KSP MUST be registered per target. A bare `ksp(...)` covers only JVM/Android and leaves
// native targets with no generated code — a green metadata compile and a broken iOS build.
dependencies {
    add("kspAndroid", libs.androidx.room3.compiler)
    add("kspJvm", libs.androidx.room3.compiler)
    add("kspIosArm64", libs.androidx.room3.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room3.compiler)
}

room3 {
    // Exported schemas are the input to migration tests. Commit this directory.
    schemaDirectory("$projectDir/schemas")
}
