package com.example.userprofile.database

import androidx.room3.ColumnInfo
import androidx.room3.ConstructedBy
import androidx.room3.Dao
import androidx.room3.Database
import androidx.room3.Entity
import androidx.room3.PrimaryKey
import androidx.room3.Query
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import androidx.room3.Upsert
import androidx.room3.migration.Migration
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import androidx.sqlite.execSQL
import kotlinx.coroutines.flow.Flow
import kotlin.coroutines.CoroutineContext

/**
 * Room 3 (`androidx.room3`, **3.0.3 stable**) — the KMP-first line: coroutine-only DAOs,
 * `SQLiteDriver` instead of `SupportSQLite`, KSP only, targets Android/iOS/JVM/web.
 * `androidx.room` 2.8.x remains the Android line. The two use different packages and
 * MUST NOT be mixed. See references/libraries/room-datastore.md.
 *
 * This is the storage shape behind `data/UserEntity.kt`. It is kept in its own package so
 * the repository's `UserLocalDataSource` interface stays independent of Room — the
 * repository tests use an in-memory fake; this file has its own DAO test.
 */
@Entity(tableName = "user")
internal data class UserRow(
    @PrimaryKey val id: String,
    val displayName: String,
    val email: String,
    val avatarUrl: String?,
    // Added in schema version 2. A NEW non-null column MUST carry a defaultValue, or the
    // migration fails on every existing row ("NOT NULL constraint failed").
    @ColumnInfo(name = "is_bookmarked", defaultValue = "0") val isBookmarked: Boolean = false,
)

@Dao
internal interface UserRowDao {
    /** Blocking DAO functions do not compile in Room 3 / KMP; everything is `suspend` or `Flow`. */
    @Upsert
    suspend fun upsert(row: UserRow)

    @Query("SELECT * FROM user WHERE id = :id")
    fun observe(id: String): Flow<UserRow?>

    @Query("SELECT COUNT(*) FROM user")
    suspend fun count(): Int
}

@Database(entities = [UserRow::class], version = 2, exportSchema = true)
@ConstructedBy(AppDatabaseConstructor::class)
internal abstract class AppDatabase : RoomDatabase() {
    abstract fun userRowDao(): UserRowDao
}

/** The KMP constructor hook. The `actual` is generated by KSP — hence the suppression. */
@Suppress("KotlinNoActualForExpect")
internal expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Common configuration applied to a platform-supplied builder. The builder itself needs
 * a platform path (`getDatabasePath` / `NSDocumentDirectory`) and so is created in the
 * platform DI module; the driver and query context are the same everywhere.
 */
internal fun RoomDatabase.Builder<AppDatabase>.configure(
    queryContext: CoroutineContext,
): AppDatabase =
    setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(queryContext)
        .addMigrations(MIGRATION_1_2)
        // Deliberately NO fallbackToDestructiveMigration: in a shipping build it converts a
        // migration bug into silent data loss. See references/libraries/room-datastore.md.
        .build()

/**
 * 1 → 2: additive, with a default, so existing rows survive. Two Room 3 differences from Room 2
 * that the compiler enforces: `migrate` receives a `SQLiteConnection` (not
 * `SupportSQLiteDatabase`) and is a **`suspend`** function. Verified by
 * jvmTest/.../AppDatabaseMigrationTest, which seeds a row at v1 and asserts it after migrating.
 */
internal val MIGRATION_1_2: Migration = object : Migration(1, 2) {
    override suspend fun migrate(connection: SQLiteConnection) {
        connection.execSQL("ALTER TABLE user ADD COLUMN is_bookmarked INTEGER NOT NULL DEFAULT 0")
    }
}
